version: "3.1"

services:
  tomcat:
    image: bitnami/tomcat:latest
    environment:
      - TOMCAT_USERNAME=root
      - TOMCAT_PASSWORD=password
    links:
      - db:mysql
    ports:
      - 8585:8080
    volumes:
      - ./tomcat:/bitnami/tomcat

  db:
    image: postgres
    container_name: db
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - 5433:5432
    environment:
      - POSTGRES_USER=vnikulshin
      - POSTGRES_PASSWORD=admin

volumes:
  db-data: