version: "3.1"

services:
  limitid:
    build:
      context: .
    container_name: limitid
    ports:
      - "9090:8080"
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/postgres

  db:
    image: postgres
    container_name: db
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=vnikulshin
      - POSTGRES_PASSWORD=admin

volumes:
  db-data:
