version: "3.1"

services:
  db:
    image: postgres
    container_name: db
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=vnikulshin
      - POSTGRES_PASSWORD=admin

volumes:
  db-data:
