server:
  servlet:
    context-path: /limitid


spring:
  datasource:
    url: jdbc:postgresql://192.168.30.153:5432/postgres
    username: vnikulshin
    password: admin
    driver-class-name: org.postgresql.Driver
    initialization-mode: always
    schema: classpath*:sql/initDB.sql

  jpa:
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQL10Dialect
    show-sql: false
bot:
  name: VNikulshin_bot
  token: 1512700278:AAHworP0q1zZLRuh7VuiKtRhcqXnBsNWwXo


